using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlaidQuickstartBlazor.Shared;

/// <summary>
/// An error generated by the Plaid service
/// </summary>
public class PlaidError
{
    public string error_type { get; set; }
    public string error_code { get; set; }
    public string error_message { get; set; } = string.Empty;
    public string? display_message { get; set; }
}
